backend:
  name: git-gateway
  repo: photocurio/dave-gentry
  branch: main-fork
media_folder: "src/pics"
public_folder: "/pics"
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subhead", name: "subhead", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Background Image", name: "backgroundImg", widget: "image" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Style", name: "style", widget: "select", options: ["light", "dark"] }
      - { label: "Layout", name: "layout", widget: "select", options: ["default", "page.html"] }
